### ISSUE TITLE
Update "The Algorithm"

### ISSUE THREAD

**Issue by yamiteru** [yamiteru/isitfast#38]
I get easily overwhelmed by a big scope which is why I've created this issue so I can split this big scope into smaller ones.

- [X] [Run benchmarks outside of Suite](https://github.com/yamiteru/isitfast/issues/39)
- [X] [Run benchmarks in a different thread](https://github.com/yamiteru/isitfast/issues/37)
- [X] [Return best case, worst case and normal case](https://github.com/yamiteru/isitfast/issues/36)
- [X] [Number of cycles being the goal and not the actual number of runs](https://github.com/yamiteru/isitfast/issues/35)
